import java.io.Serializable;

public class Mercenary implements Serializable {

    //Attributes
    String name;
    Weapon primary;
    Weapon secondary;
    Weapon tertiary;
    private static final long serialVersionUID = 1L; //If a class does not explicitly define a private static final long serialVersionUID in the code it will be autogenerated,


    //Methods
    public void battleCry(){
         System.out.println(("My name is "+name+", prepare to die!"));
    }

    public void dumpMercenaryInfo(){
        System.out.println("Name: "+this.name);

        System.out.println("Primary:");
        this.primary.dumpWeapon();

        System.out.println("Secondary:");
        this.secondary.dumpWeapon();

        System.out.println("Tertiary:");
        this.tertiary.dumpWeapon();

    }


    //Constructor
    public Mercenary(String name, Weapon primary, Weapon secondary, Weapon tertiary){
        this.name = name;
        this.primary = primary;
        this.secondary= secondary;
        this.tertiary = tertiary;

    }

    public Mercenary(String name){
        this.name = name;


    }

    public Mercenary() {
    }
}

