import java.io.Serializable;

public class Sword extends Weapon implements Serializable {

    int amountOfHands;
    private static final long serialVersionUID = 1L; //If a class does not explicitly define a private static final long serialVersionUID in the code it will be autogenerated,


    public Sword(String type, String name, int attack, int speed, int block,int cost, int amountOfHands) {
        super(type, name, attack, speed, block,cost);
        this.amountOfHands = amountOfHands;
    }



}
