import java.io.Serializable;

public class Weapon implements Serializable {

    public String type;
    public String name;
    public int attack;
    public int speed;
    public int block;
    public int cost;
    private static final long serialVersionUID = 1L; //If a class does not explicitly define a private static final long serialVersionUID in the code it will be autogenerated,



    public Weapon(String type, String name, int attack, int speed, int block, int cost) {
        this.type = type;
        this.name = name;
        this.attack = attack;
        this.speed = speed;
        this.block = block;
        this.cost = cost;
    }

    public Weapon() {
        super();
    }


    public void dumpWeapon(){

        if(this.name != null) {
            System.out.println("Type: ["+this.type+"]     Name: ["+this.name+"]     Attack: "+this.attack+" Speed: "+this.speed+" Block: "+this.block+" Cost: "+this.cost);
        }else{
            System.out.println("Empty");
        }


    }

}
